version: "2.2"

services:
  redis:
    image: redis
    command: redis-server
    ports:
      - "${DOCKER_BASE_REDIS_SERVER_PORT:-14000}:6379" #Redis server

  autocampus-icu-backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: AutOCampus-ICU-Backend
    command: python3 app/autOCampus-icu-backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "${DOCKER_BASE_APP_PORT:-8000}:8000" # Web app
    restart: "always"
    links:
      - redis
    depends_on:
      - redis
  autocampus-icu-frontend:
      build:
         context: ./app/autOCampus-icu-frontend
         dockerfile: Dockerfile
      container_name: AutOCampus-ICU-Frontend
      volumes:
         - ./app/autOCampus-icu-frontend:/app
         - /app/node_modules
      ports:
        - "${DOCKER_BASE_REACT_APP_PORT:-3000}:3000"    # React app
      stdin_open: true
      depends_on:
         - autocampus-icu-backend
    
